apiVersion: v1
kind: Namespace
metadata:
  name: non-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: non-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/nonprod-eks-usw2-alb-sa-role
